# fly.toml app configuration file generated for vibz-proud-meadow-2288 on 2025-08-14T08:29:44-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vibz-proud-meadow-2288'
primary_region = 'sea'

[experimental]
  auto_rollback = true

[build]

[env]


[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 4
