# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class McpFilesBucket:
        name: str
        type: str
    class McpVpc:
        type: str

